### ISSUE TITLE
Tensorflow annotation

### ISSUE THREAD

**Issue by StephanieHowe** [tare/Span#1]
Hi, thank you for sharing this! 

I have some mouse lumbar spinal cord samples I'm trying to annotate, and was wondering if you would consider adding your model to the repository? I can't seem to add the lumbar spinal cord template (I have changed const TENSORFLOW_ANNOTATION to true), and I think it's because the html code refers to a dropbox file:

if (TENSORFLOW_ANNOTATION) {
      // tensorflow.js
      async function loadModel() {
        const model = await tf.loadModel('https://dl.dropboxusercontent.com/s/ix9r5cgy2uba2x3/model.json');
        return model;
      };

Thank you again for sharing this resource, and I apologise if I have just misinterpreted the code!

**Comment by tare** [comment]
Thank you for your message! Yes, you did identify the issue correctly.

Could you please check whether the code in the [dev](/tare/Span/tree/dev) branch works for you. I seem to run it without issues in Chrome but not in Safari.

In addition to fixing the broken links, I did push the model files. 

All this code was written for the original ST array design, therefore there might some assumptions that don't hold in the case of Visium.

**Comment by StephanieHowe** [comment]
Hi, thanks so much for the fast reply! The dev branch code works for me in Chrome and Firefox.
